Fix TypeError
File "/opt/digits/digits/extensions/data/imageSegmentation/data.py", line 225, in split_image_list
random.shuffle(self.random_indices)
File "/usr/lib/python3.8/random.py", line 307, in shuffle
x[i], x[j] = x[j], x[i]
TypeError: 'range' object does not support item assignment