Upgrade caffe_train_task.network object type
Convert from NetParameter to string back to NetParameter to avoid this
error:

TypeError: Parameter to MergeFrom() must be instance of same class:
        expected caffe_pb2.NetParameter got
        caffe.proto.caffe_pb2.NetParameter.